[build]
  command = "npx pnpm install --no-frozen-lockfile && npx pnpm run build"
  publish = "dist"

[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 